# Generated by Django 3.1.2 on 2020-12-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetmedaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='done',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
