# Generated by Django 3.1.2 on 2020-12-20 17:57

from django.db import migrations, models
import meetmedaccount.models


class Migration(migrations.Migration):

    dependencies = [
        ('meetmedaccount', '0002_auto_20201220_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='done',
            field=models.CharField(default=meetmedaccount.models.defaultDoneClass, max_length=30),
        ),
    ]
