# Generated by Django 3.1.2 on 2021-01-05 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetmedaccount', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor', models.CharField(max_length=30)),
                ('note', models.CharField(max_length=1500)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetmedaccount.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
