# Generated by Django 3.1.2 on 2021-01-05 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetmedaccount', '0006_auto_20210105_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentnote',
            name='doctor',
        ),
    ]
